version: '3.9'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=@SQL2023douglas
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - sql_server_network

volumes:
  sql_data:

networks:
  sql_server_network:
    driver: bridge